### ISSUE TITLE
"Illegal instruction: 4" when ^C in an empty prompt

### ISSUE THREAD

**Issue by willfaught** [bobappleyard/readline#18]
Ran this code with OS X 10.10 Terminal, full screen, bash, Command Line Tools, and readline (via Homebrew):

	for {
		l, err := readline.String("> ")
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Println("error: ", err)
			break
		}
		if l != "" {
			fmt.Println(l)
		}
		readline.AddHistory(l)
	}

I entered this:

    $ myprogram
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > ls
    ls
    > hello
    hello
    > ^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C[...]C^C^C^C^C^C^C^C^C^C^CIllegal instruction: 4

and it printed thousands of "^C" followed by "Illegal instruction: 4".

Can't reproduce it.

**Comment by bobappleyard** [comment]
I don't have OS X so I can't try to reproduce it at the moment.

I know someone who has so I will see if I can get some time with their compute at some point in the near future.

**Comment by willfaught** [comment]
I saw it happen again, FWIW. Ctrl-C with no other input and a non-empty prompt.

**Comment by mcuadros** [comment]
same problem here

**Comment by willfaught** [comment]
Thanks for the fix!
