### ISSUE TITLE
print thousands of ^C when press ^C

### ISSUE THREAD

**Issue by chzyer** [bobappleyard/readline#20]
When I press ^C intend to exit, sometime it cause follows in ubuntu.
```
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CSegmentation fault (core dumped)
```
But I can't reproduce it everytime.

I try to set `CatchSigint` to false and catch os.Interrupt myself and call `os.Exit` immediately, but still not working.

**Comment by xyproto** [comment]
I have also experienced problems catching ^C when using this package, but I'm not 100% sure if it is this package, [graceful](https://github.com/tylerb/graceful) or OS X that is causing it.

**Comment by chzyer** [comment]
@xyproto, I have found a solution. ^C always cause by press ^C in the first run after `go build` it(still don't know why).

Try to move 
```
C.rl_catch_signals = 0
C.rl_catch_sigwinch = 0
```
out from `handleSignals` to init before `register_readline`.

**Comment by bobappleyard** [comment]
Are you going to submit a pull request, or shall I direct people to your repo?

**Comment by chzyer** [comment]
I pulled. :) #22

**Comment by bobappleyard** [comment]
Brilliant, thanks
